/**
 * DynamoDB table resource.
 *
 * Single-table design (see DECISIONS.md "Data model: single-table design"): PK = item
 * id, SK distinguishes the record kind sharing that partition (`latest`, `VERSION#`,
 * `AUDIT#` — see `src/storage/single-table-keys.ts`). Physical table name is
 * auto-generated by SST as `app-stage-name-<random>`, already keyed off the raw
 * `$app.stage` — so concurrent personal `sst dev` stages never collide on the same
 * table (see `infra/stage.ts` for why that matters).
 *
 * `GSI1`/`GSI2` back `listItems`'s subject/status filters with a `Query` instead of a
 * `Scan` (see `src/storage/dynamodb.ts` and `single-table-keys.ts`). `GSI1PK`/`GSI1SK`
 * and `GSI2PK`/`GSI2SK` are only ever written on the `latest` record, so both indexes
 * are sparse — they only ever contain one entry per item, never `VERSION#`/`AUDIT#`
 * rows, with no extra filtering needed on either index.
 */
export function createExamItemsTable() {
  return new sst.aws.Dynamo('ExamItemsTable', {
    fields: {
      PK: 'string',
      SK: 'string',
      GSI1PK: 'string',
      GSI1SK: 'string',
      GSI2PK: 'string',
      GSI2SK: 'string',
    },
    primaryIndex: { hashKey: 'PK', rangeKey: 'SK' },
    globalIndexes: {
      GSI1: { hashKey: 'GSI1PK', rangeKey: 'GSI1SK' },
      GSI2: { hashKey: 'GSI2PK', rangeKey: 'GSI2SK' },
    },
  });
}
