/**
 * DynamoDB table resource.
 *
 * Single-table design (see DECISIONS.md "Data model: single-table design"): PK = item
 * id, SK distinguishes the record kind sharing that partition (`latest`, `VERSION#`,
 * `AUDIT#` — see `src/storage/single-table-keys.ts`). Physical table name is
 * auto-generated by SST as `app-stage-name-<random>`, already keyed off the raw
 * `$app.stage` — so concurrent personal `sst dev` stages never collide on the same
 * table (see `infra/stage.ts` for why that matters).
 */
export function createExamItemsTable() {
  return new sst.aws.Dynamo('ExamItemsTable', {
    fields: {
      PK: 'string',
      SK: 'string',
    },
    primaryIndex: { hashKey: 'PK', rangeKey: 'SK' },
  });
}
